services:
  easytier:
    environment:
      EASYTIER_PROTOCOL: ${EASYTIER_PROTOCOL:-tcp}
      EASYTIER_PORT: ${EASYTIER_PORT:-11010}
      EASYTIER_PUBLIC_IP: ${EASYTIER_PUBLIC_IP}
      ET_PEERS: ${ET_PEERS:-${EASYTIER_PROTOCOL:-tcp}://${EASYTIER_PUBLIC_IP}:${EASYTIER_PORT:-11010}}
